name: docker hub release

on:
  push:
    tags:
    - 'v*'

jobs:
  buildx-dockerhub:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: airene/dnspod-go
      DOCKER_PLATFORMS: linux/amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare arguments
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> ${GITHUB_ENV}

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run buildx and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ env.DOCKER_PLATFORMS }}
          tags: |
            ${{ env.DOCKER_REPO }}:latest
            ${{ env.DOCKER_REPO }}:${{ env.VERSION }}
